In [35]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv('C:\K\social-media-dev-crawler\data\preprocessed_full_posts.csv')
df.head()

<>:4: SyntaxWarning: invalid escape sequence '\K'
<>:4: SyntaxWarning: invalid escape sequence '\K'
C:\Users\RESET Lab\AppData\Local\Temp\ipykernel_16892\1310106613.py:4: SyntaxWarning: invalid escape sequence '\K'
  df = pd.read_csv('C:\K\social-media-dev-crawler\data\preprocessed_full_posts.csv')

,site_alias,tags,question_id,accepted_answer_id,answer_count,creation_date,last_activity_date,last_edit_date,owner_id,score,view_count,comment_count,title,body,site,id,type,code
0,crypto.stackexchange.com.7z,passwords;hash;salt,12795,12817.0,2.0,2014-01-08T23:01:58.563,2014-01-10T04:37:57.020,2017-05-23T12:41:34.263,11310.0,8.0,3377.0,16.0,Why do I need to add the original salt to each...,I understand it is important to hash passwords...,crypto.stackexchange.com.7z,12795,question,var hash = sha512(salt + password); \nfor (i =...
1,crypto.stackexchange.com.7z,cryptanalysis;file-encryption,72384,NaN,7.0,2019-08-05T11:28:18.697,2019-08-08T01:08:37.403,2019-08-07T18:27:14.967,8532.0,18.0,23047.0,14.0,How to check a file was encrypted (really & co...,I would like to audit how an implementation of...,crypto.stackexchange.com.7z,72384,question,NaN
2,crypto.stackexchange.com.7z,symmetric;encryption;hash;public-key,5861,5863.0,2.0,2012-12-30T16:57:14.387,2012-12-31T00:13:51.710,2012-12-30T18:34:17.873,549.0,6.0,10486.0,10.0,Difference between symmetric and asymmetric ha...,The Linux kernel supports symmetric and asymme...,crypto.stackexchange.com.7z,5861,question,NaN
3,crypto.stackexchange.com.7z,rsa;cpu;implementation,35586,35594.0,5.0,2016-05-26T08:55:11.900,2021-06-01T19:15:38.887,2020-06-17T08:17:00.433,34404.0,41.0,10363.0,6.0,"In RSA, how does the CPU deal with this huge m...",Whilst I understand how the RSA algorithm work...,crypto.stackexchange.com.7z,35586,question,NaN
4,crypto.stackexchange.com.7z,cryptanalysis;key-reuse;one-time-pad,2249,2250.0,3.0,2012-03-31T22:29:02.540,2016-01-31T10:22:32.350,2017-04-13T12:48:24.517,1867.0,79.0,93925.0,5.0,How does one attack a two-time pad (i.e. one t...,My question might appear the same as the quest...,crypto.stackexchange.com.7z,2249,question,NaN

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4386 entries, 0 to 4385
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   site_alias          4386 non-null   object
 1   tags                284 non-null    object
 2   question_id         4386 non-null   int64
 3   accepted_answer_id  204 non-null    float64
 4   answer_count        4386 non-null   float64
 5   creation_date       4386 non-null   object
 6   last_activity_date  1706 non-null   object
 7   last_edit_date      905 non-null    object
 8   owner_id            4197 non-null   float64
 9   score               4386 non-null   float64
 10  view_count          4386 non-null   float64
 11  comment_count       4386 non-null   float64
 12  title               284 non-null    object
 13  body                4386 non-null   object
 14  site                4386 non-null   object
 15  id                  4386 non-null   int64
 16  type                4386 non-null   object
 17  code                437 non-null    object
dtypes: float64(6), int64(2), object(10)
memory usage: 616.9+ KB

In [37]:
questions = df[df['type'] == 'question']
answers = df[df['type'] == 'answer']

In [38]:
questions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 284 entries, 0 to 283
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   site_alias          284 non-null    object
 1   tags                284 non-null    object
 2   question_id         284 non-null    int64
 3   accepted_answer_id  204 non-null    float64
 4   answer_count        284 non-null    float64
 5   creation_date       284 non-null    object
 6   last_activity_date  284 non-null    object
 7   last_edit_date      241 non-null    object
 8   owner_id            273 non-null    float64
 9   score               284 non-null    float64
 10  view_count          284 non-null    float64
 11  comment_count       284 non-null    float64
 12  title               284 non-null    object
 13  body                284 non-null    object
 14  site                284 non-null    object
 15  id                  284 non-null    int64
 16  type                284 non-null    object
 17  code                177 non-null    object
dtypes: float64(6), int64(2), object(10)
memory usage: 42.2+ KB

In [39]:
answers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1422 entries, 284 to 2515
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   site_alias          1422 non-null   object
 1   tags                0 non-null      object
 2   question_id         1422 non-null   int64
 3   accepted_answer_id  0 non-null      float64
 4   answer_count        1422 non-null   float64
 5   creation_date       1422 non-null   object
 6   last_activity_date  1422 non-null   object
 7   last_edit_date      664 non-null    object
 8   owner_id            1371 non-null   float64
 9   score               1422 non-null   float64
 10  view_count          1422 non-null   float64
 11  comment_count       1422 non-null   float64
 12  title               0 non-null      object
 13  body                1422 non-null   object
 14  site                1422 non-null   object
 15  id                  1422 non-null   int64
 16  type                1422 non-null   object
 17  code                260 non-null    object
dtypes: float64(6), int64(2), object(10)
memory usage: 211.1+ KB

In [41]:
na_q = questions[pd.isna(questions['code'])]
na_q.head()

,site_alias,tags,question_id,accepted_answer_id,answer_count,creation_date,last_activity_date,last_edit_date,owner_id,score,view_count,comment_count,title,body,site,id,type,code
1,crypto.stackexchange.com.7z,cryptanalysis;file-encryption,72384,NaN,7.0,2019-08-05T11:28:18.697,2019-08-08T01:08:37.403,2019-08-07T18:27:14.967,8532.0,18.0,23047.0,14.0,How to check a file was encrypted (really & co...,I would like to audit how an implementation of...,crypto.stackexchange.com.7z,72384,question,NaN
2,crypto.stackexchange.com.7z,symmetric;encryption;hash;public-key,5861,5863.0,2.0,2012-12-30T16:57:14.387,2012-12-31T00:13:51.710,2012-12-30T18:34:17.873,549.0,6.0,10486.0,10.0,Difference between symmetric and asymmetric ha...,The Linux kernel supports symmetric and asymme...,crypto.stackexchange.com.7z,5861,question,NaN
3,crypto.stackexchange.com.7z,rsa;cpu;implementation,35586,35594.0,5.0,2016-05-26T08:55:11.900,2021-06-01T19:15:38.887,2020-06-17T08:17:00.433,34404.0,41.0,10363.0,6.0,"In RSA, how does the CPU deal with this huge m...",Whilst I understand how the RSA algorithm work...,crypto.stackexchange.com.7z,35586,question,NaN
4,crypto.stackexchange.com.7z,cryptanalysis;key-reuse;one-time-pad,2249,2250.0,3.0,2012-03-31T22:29:02.540,2016-01-31T10:22:32.350,2017-04-13T12:48:24.517,1867.0,79.0,93925.0,5.0,How does one attack a two-time pad (i.e. one t...,My question might appear the same as the quest...,crypto.stackexchange.com.7z,2249,question,NaN
7,crypto.stackexchange.com.7z,random-number-generator;randomness;pseudo-rand...,87978,NaN,8.0,2021-02-04T02:21:43.363,2021-02-08T11:46:23.317,2021-02-05T00:12:22.157,86738.0,34.0,14274.0,23.0,"Why do some people believe that humans are ""ba...","I'm not even sure if they are serious, but I'v...",crypto.stackexchange.com.7z,87978,question,NaN