## Valid

In [27]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv('C:\K\social-media-dev-crawler\data\data_mining\s2\preprocessed_full_posts.csv')
df.head()

<>:4: SyntaxWarning: invalid escape sequence '\K'
<>:4: SyntaxWarning: invalid escape sequence '\K'
C:\Users\RESET Lab\AppData\Local\Temp\ipykernel_12468\277205348.py:4: SyntaxWarning: invalid escape sequence '\K'
  df = pd.read_csv('C:\K\social-media-dev-crawler\data\data_mining\s2\preprocessed_full_posts.csv')

,site_alias,tags,question_id,accepted_answer_id,answer_count,creation_date,last_activity_date,last_edit_date,owner_id,score,view_count,comment_count,title,body,site,id,type,code
0,crypto.stackexchange.com.7z,tls;rc4,853,NaN,7.0,2011-09-29T05:30:51.427,2014-08-26T20:58:28.183,2011-09-29T08:05:21.480,38.0,52.0,33198.0,4.0,"Google is using RC4, but isn't RC4 considered ...",Why is Google using RC4 for their HTTPS/SSL?\n...,crypto.stackexchange.com.7z,853,question,<code>$ openssl s_client -connect www.google.c...
1,crypto.stackexchange.com.7z,hash;passwords;salt,12795,12817.0,2.0,2014-01-08T23:01:58.563,2014-01-10T04:37:57.020,2017-05-23T12:41:34.263,11310.0,8.0,3377.0,6.0,Why do I need to add the original salt to each...,I understand it is important to hash passwords...,crypto.stackexchange.com.7z,12795,question,<code>var hash = sha512(salt + password); \nfo...
2,crypto.stackexchange.com.7z,hash;passwords;authentication,3082,3084.0,5.0,2012-06-27T17:48:29.353,2018-10-25T20:09:34.627,2020-06-17T08:17:00.433,2392.0,8.0,12205.0,6.0,How can I validate a hashed password if all I ...,The Scenario\nI have a client-side web applica...,crypto.stackexchange.com.7z,3082,question,<code>GET http://application.url/endpoint?user...
3,crypto.stackexchange.com.7z,hash;reference-request;sha-3;xof,30587,30594.0,2.0,2015-11-16T15:09:27.017,2021-02-11T02:53:37.930,2019-05-18T10:50:44.380,28013.0,20.0,7903.0,9.0,Use case for extendable-output functions (XOF)...,"FIPS 202 defines 2 functions, SHAKE128 and SHA...",crypto.stackexchange.com.7z,30587,question,"<code>SHAKE128(keymaterial, keylength)</code>"
4,crypto.stackexchange.com.7z,chacha;stream-cipher,70094,70112.0,3.0,2019-04-26T22:37:10.927,2019-05-14T01:54:29.397,2021-10-07T07:59:29.080,28046.0,6.0,4432.0,4.0,Does ChaCha20 counter actually increment throu...,RFC defines:\n\n<code>state = constants | key ...,crypto.stackexchange.com.7z,70094,question,<code>state = constants | key | counter | nonc...

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1002 entries, 0 to 1001
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   site_alias          1002 non-null   object
 1   tags                606 non-null    object
 2   question_id         1002 non-null   int64
 3   accepted_answer_id  442 non-null    float64
 4   answer_count        1002 non-null   float64
 5   creation_date       1002 non-null   object
 6   last_activity_date  1002 non-null   object
 7   last_edit_date      756 non-null    object
 8   owner_id            967 non-null    float64
 9   score               1002 non-null   float64
 10  view_count          1002 non-null   float64
 11  comment_count       1002 non-null   float64
 12  title               606 non-null    object
 13  body                1002 non-null   object
 14  site                1002 non-null   object
 15  id                  1002 non-null   int64
 16  type                1002 non-null   object
 17  code                1002 non-null   object
dtypes: float64(6), int64(2), object(10)
memory usage: 141.0+ KB

In [29]:
questions = df[df['type'] == 'question']
answers = df[df['type'] == 'answer']

In [30]:
questions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 606 entries, 0 to 605
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   site_alias          606 non-null    object
 1   tags                606 non-null    object
 2   question_id         606 non-null    int64
 3   accepted_answer_id  442 non-null    float64
 4   answer_count        606 non-null    float64
 5   creation_date       606 non-null    object
 6   last_activity_date  606 non-null    object
 7   last_edit_date      512 non-null    object
 8   owner_id            583 non-null    float64
 9   score               606 non-null    float64
 10  view_count          606 non-null    float64
 11  comment_count       606 non-null    float64
 12  title               606 non-null    object
 13  body                606 non-null    object
 14  site                606 non-null    object
 15  id                  606 non-null    int64
 16  type                606 non-null    object
 17  code                606 non-null    object
dtypes: float64(6), int64(2), object(10)
memory usage: 90.0+ KB

In [31]:
answers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 396 entries, 606 to 1001
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   site_alias          396 non-null    object
 1   tags                0 non-null      object
 2   question_id         396 non-null    int64
 3   accepted_answer_id  0 non-null      float64
 4   answer_count        396 non-null    float64
 5   creation_date       396 non-null    object
 6   last_activity_date  396 non-null    object
 7   last_edit_date      244 non-null    object
 8   owner_id            384 non-null    float64
 9   score               396 non-null    float64
 10  view_count          396 non-null    float64
 11  comment_count       396 non-null    float64
 12  title               0 non-null      object
 13  body                396 non-null    object
 14  site                396 non-null    object
 15  id                  396 non-null    int64
 16  type                396 non-null    object
 17  code                396 non-null    object
dtypes: float64(6), int64(2), object(10)
memory usage: 58.8+ KB

## Invalid

In [32]:
df = pd.read_csv(r'C:\K\social-media-dev-crawler\data\data_mining\s2\invalid_codes.csv')
df.head()

,site_alias,tags,question_id,accepted_answer_id,answer_count,creation_date,last_activity_date,last_edit_date,owner_id,score,view_count,comment_count,title,body,site,id,type,code
0,crypto.stackexchange.com.7z,file-encryption;cryptanalysis,72384,NaN,7.0,2019-08-05T11:28:18.697,2019-08-08T01:08:37.403,2019-08-07T18:27:14.967,8532.0,18.0,23047.0,11.0,How to check a file was encrypted (really & co...,I would like to audit how an implementation of...,crypto.stackexchange.com.7z,72384,question,<code>ent</code>
1,crypto.stackexchange.com.7z,public-key;hash;encryption;symmetric,5861,5863.0,2.0,2012-12-30T16:57:14.387,2012-12-31T00:13:51.710,2012-12-30T18:34:17.873,549.0,6.0,10486.0,10.0,Difference between symmetric and asymmetric ha...,The Linux kernel supports symmetric and asymme...,crypto.stackexchange.com.7z,5861,question,<code>test_hash_speed</code>\n\n<code>test_aha...
2,crypto.stackexchange.com.7z,rsa;implementation;cpu,35586,35594.0,5.0,2016-05-26T08:55:11.900,2021-06-01T19:15:38.887,2020-06-17T08:17:00.433,34404.0,41.0,10363.0,6.0,"In RSA, how does the CPU deal with this huge m...",Whilst I understand how the RSA algorithm work...,crypto.stackexchange.com.7z,35586,question,<code>mod</code>
3,crypto.stackexchange.com.7z,key-reuse;one-time-pad;cryptanalysis,2249,2250.0,3.0,2012-03-31T22:29:02.540,2016-01-31T10:22:32.350,2017-04-13T12:48:24.517,1867.0,79.0,93925.0,5.0,How does one attack a two-time pad (i.e. one t...,My question might appear the same as the quest...,crypto.stackexchange.com.7z,2249,question,<code>' '</code>\n\n<code>' '</code>
4,crypto.stackexchange.com.7z,elliptic-curves;diffie-hellman;openssl;key-der...,28930,28936.0,2.0,2015-09-04T04:40:10.110,2020-12-03T08:44:18.490,2015-09-04T07:59:06.247,26382.0,11.0,8165.0,4.0,How to derive a symmetric key from ECDH shared...,I am trying to implement the internal primitiv...,crypto.stackexchange.com.7z,28930,question,"<code>...\nprint_hex(hash_input_buffer, shared..."