## Valid

In [25]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv('C:\K\social-media-dev-crawler\data\data_mining\s2\preprocessed_full_posts.csv')
df.head()

,site_alias,tags,question_id,accepted_answer_id,answer_count,creation_date,last_activity_date,last_edit_date,owner_id,score,view_count,comment_count,title,body,site,id,type,code,languages
0,crypto,ciphertext-only-attack;one-time-pad;xor;key-reuse,88430,88496.0,2.0,2021-02-23T10:52:00.590,2024-11-14T19:00:56.130,2021-02-26T14:25:04.713,3941.0,4,18093.0,10.0,How to decrypt two images encrypted using XOR ...,I am trying to solve the following puzzle from...,crypto.stackexchange.com.7z,88430,question,<code>from binascii import unhexlify\n\nwith o...,{'python': 1}
1,crypto,chacha;stream-cipher,70094,70112.0,3.0,2019-04-26T22:37:10.927,2019-05-14T01:54:29.397,2021-10-07T07:59:29.080,28046.0,6,4432.0,4.0,Does ChaCha20 counter actually increment throu...,RFC defines:\n\n<code>state = constants | key ...,crypto.stackexchange.com.7z,70094,question,<code>state = constants | key | counter | nonc...,{'python': 1}
2,crypto,ctr;aes;cryptocurrency,55014,55044.0,2.0,2018-01-25T15:33:08.797,2018-01-30T15:51:38.750,2018-01-26T11:07:05.477,55389.0,4,19846.0,5.0,How insecure is AES-128-CTR to encrypt any kin...,I am using the Ethereum keystore file format t...,crypto.stackexchange.com.7z,55014,question,"<code>MY_PASSWORD = ""VeryDifficultPasword43213...",{'python': 1}
3,crypto,public-key;prime-numbers;keys;rsa;certificates,12378,NaN,2.0,2013-12-16T22:53:54.490,2017-07-06T11:56:34.173,2013-12-16T23:11:16.457,10912.0,6,7324.0,5.0,What exactly is inside a private key?,"May sound stupid to many, but I would like to ...",crypto.stackexchange.com.7z,12378,question,<code>openssl genrsa\n</code>,{'c_sharp': 1}
4,crypto,implementation;cryptanalysis;hash,300,332.0,3.0,2011-08-03T15:18:26.927,2016-05-22T15:09:14.567,2015-11-13T09:40:39.803,316.0,20,11103.0,5.0,Cryptanalysis to reverse engineer a hash?,I understand this may not be the best place to...,crypto.stackexchange.com.7z,300,question,<code>D = 0\nE = 1\nF = 2\nG = 3\nH = 4\nI = 5...,{'python': 1}

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2903 entries, 0 to 2902
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   site_alias          2903 non-null   object
 1   tags                39 non-null     object
 2   question_id         2903 non-null   int64
 3   accepted_answer_id  29 non-null     float64
 4   answer_count        2903 non-null   float64
 5   creation_date       2903 non-null   object
 6   last_activity_date  471 non-null    object
 7   last_edit_date      212 non-null    object
 8   owner_id            2779 non-null   float64
 9   score               2903 non-null   int64
 10  view_count          2903 non-null   float64
 11  comment_count       2903 non-null   float64
 12  title               39 non-null     object
 13  body                2903 non-null   object
 14  site                2903 non-null   object
 15  id                  2903 non-null   int64
 16  type                2903 non-null   object
 17  code                90 non-null     object
 18  languages           90 non-null     object
dtypes: float64(5), int64(3), object(11)
memory usage: 431.0+ KB

In [27]:
df.drop_duplicates(inplace=True)

In [28]:
df.shape

(2903, 19)

In [29]:
questions = df[df['type'] == 'question']
answers = df[df['type'] == 'answer']

In [30]:
questions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 39 entries, 0 to 856
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   site_alias          39 non-null     object
 1   tags                39 non-null     object
 2   question_id         39 non-null     int64
 3   accepted_answer_id  29 non-null     float64
 4   answer_count        39 non-null     float64
 5   creation_date       39 non-null     object
 6   last_activity_date  39 non-null     object
 7   last_edit_date      32 non-null     object
 8   owner_id            38 non-null     float64
 9   score               39 non-null     int64
 10  view_count          39 non-null     float64
 11  comment_count       39 non-null     float64
 12  title               39 non-null     object
 13  body                39 non-null     object
 14  site                39 non-null     object
 15  id                  39 non-null     int64
 16  type                39 non-null     object
 17  code                39 non-null     object
 18  languages           39 non-null     object
dtypes: float64(5), int64(3), object(11)
memory usage: 6.1+ KB

In [31]:
questions.iloc[9]['code']

'<code>{00000010}</code>\n\n<code>{02}</code>'

In [32]:
answers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 432 entries, 19 to 1157
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   site_alias          432 non-null    object
 1   tags                0 non-null      object
 2   question_id         432 non-null    int64
 3   accepted_answer_id  0 non-null      float64
 4   answer_count        432 non-null    float64
 5   creation_date       432 non-null    object
 6   last_activity_date  432 non-null    object
 7   last_edit_date      180 non-null    object
 8   owner_id            419 non-null    float64
 9   score               432 non-null    int64
 10  view_count          432 non-null    float64
 11  comment_count       432 non-null    float64
 12  title               0 non-null      object
 13  body                432 non-null    object
 14  site                432 non-null    object
 15  id                  432 non-null    int64
 16  type                432 non-null    object
 17  code                51 non-null     object
 18  languages           51 non-null     object
dtypes: float64(5), int64(3), object(11)
memory usage: 67.5+ KB

In [33]:
p = df[(df['question_id'] == 8695) & (df['type'] == 'question')]
p

Empty DataFrame
Columns: [site_alias, tags, question_id, accepted_answer_id, answer_count, creation_date, last_activity_date, last_edit_date, owner_id, score, view_count, comment_count, title, body, site, id, type, code, languages]
Index: []

In [34]:
p = df[df['question_id'] == 12378]
p

,site_alias,tags,question_id,accepted_answer_id,answer_count,creation_date,last_activity_date,last_edit_date,owner_id,score,view_count,comment_count,title,body,site,id,type,code,languages
3,crypto,public-key;prime-numbers;keys;rsa;certificates,12378,NaN,2.0,2013-12-16T22:53:54.490,2017-07-06T11:56:34.173,2013-12-16T23:11:16.457,10912.0,6,7324.0,5.0,What exactly is inside a private key?,"May sound stupid to many, but I would like to ...",crypto.stackexchange.com.7z,12378,question,<code>openssl genrsa\n</code>,{'c_sharp': 1}
102,crypto,NaN,12378,NaN,0.0,2017-07-05T10:44:06.590,2017-07-06T11:56:34.173,2017-07-06T11:56:34.173,48332.0,2,0.0,1.0,NaN,"Firstly, there are two common formats to store...",crypto.stackexchange.com.7z,48864,answer,NaN,NaN
405,crypto,NaN,12378,NaN,0.0,2013-12-16T23:16:06.777,NaN,NaN,5231.0,0,0.0,0.0,NaN,Try the [`pkey`](https://www.openssl.org/docs/...,crypto.stackexchange.com.7z,26390,comment,NaN,NaN
406,crypto,NaN,12378,NaN,0.0,2013-12-16T23:37:33.660,NaN,NaN,10912.0,0,0.0,0.0,NaN,thx rath for the pointer. The following comman...,crypto.stackexchange.com.7z,26391,comment,NaN,NaN
407,crypto,NaN,12378,NaN,0.0,2013-12-16T23:59:20.083,NaN,NaN,5231.0,4,0.0,0.0,NaN,Good to know. May I suggest that you write an ...,crypto.stackexchange.com.7z,26393,comment,NaN,NaN
414,crypto,NaN,12378,NaN,0.0,2013-12-19T19:24:58.393,NaN,NaN,214.0,3,0.0,0.0,NaN,This question appears to be off-topic because ...,crypto.stackexchange.com.7z,26596,comment,NaN,NaN
660,crypto,NaN,12378,NaN,0.0,2017-07-07T04:45:14.413,NaN,NaN,12642.0,0,0.0,0.0,NaN,There's a lot more than two. OpenSSL `genrsa` ...,crypto.stackexchange.com.7z,109936,comment,NaN,NaN
662,crypto,NaN,12378,NaN,0.0,2017-12-11T23:45:57.887,NaN,NaN,52254.0,0,0.0,0.0,NaN,How many digits can n have for 1024-bit key?,crypto.stackexchange.com.7z,119198,comment,NaN,NaN
663,crypto,NaN,12378,NaN,0.0,2017-12-12T06:00:00.373,NaN,NaN,214.0,2,0.0,0.0,NaN,"@user By definition, in a 1024-bit key, $n$ ha...",crypto.stackexchange.com.7z,119209,comment,NaN,NaN
679,crypto,NaN,12378,NaN,0.0,2018-02-06T16:45:57.500,NaN,NaN,52050.0,4,0.0,0.0,NaN,Possible duplicate of [What data is saved in R...,crypto.stackexchange.com.7z,122577,comment,NaN,NaN

## Invalid

In [35]:
df = pd.read_csv(r'C:\K\social-media-dev-crawler\data\data_mining\s2\invalid_codes.csv')
df.head()

,site_alias,tags,question_id,accepted_answer_id,answer_count,creation_date,last_activity_date,last_edit_date,owner_id,score,view_count,comment_count,title,body,site,id,type,code,languages,invalid_block_preview
0,crypto,file-encryption;cryptanalysis,72384,NaN,7.0,2019-08-05T11:28:18.697,2019-08-08T01:08:37.403,2019-08-07T18:27:14.967,8532.0,18,23047.0,11.0,How to check a file was encrypted (really & co...,I would like to audit how an implementation of...,crypto.stackexchange.com.7z,72384,question,NaN,NaN,<code>ent</code>
1,crypto,one-time-pad;cryptanalysis;key-reuse,2249,2250.0,3.0,2012-03-31T22:29:02.540,2016-01-31T10:22:32.350,2017-04-13T12:48:24.517,1867.0,79,93925.0,5.0,How does one attack a two-time pad (i.e. one t...,My question might appear the same as the quest...,crypto.stackexchange.com.7z,2249,question,NaN,NaN,<code>' '</code>
2,crypto,file-encryption;rsa;signature;hash;authenticat...,8104,8116.0,5.0,2013-04-24T15:51:00.203,2018-01-31T00:56:20.663,2013-04-24T17:03:21.083,6389.0,10,7163.0,18.0,Tamper-proofing log files,Problem Overview\n\nI want to securely store l...,crypto.stackexchange.com.7z,8104,question,NaN,NaN,<code>2013-01-01.log</code>
3,crypto,aes-gcm;aes;gcm,76177,NaN,3.0,2019-12-03T17:23:42.200,2019-12-06T11:23:35.187,2019-12-04T21:03:59.350,74873.0,9,33754.0,6.0,How to encrypt files using AES256-GCM cipher u...,I'm struggling to implement AES256-GCM on a Li...,crypto.stackexchange.com.7z,76177,question,NaN,NaN,<code>$ openssl aes-256-gcm\nAEAD ciphers not ...
4,crypto,key-size;rsa;cryptanalysis;factoring,8687,8692.0,4.0,2013-06-11T16:36:12.377,2020-11-01T07:03:19.213,2017-04-13T12:48:22.170,214.0,48,38477.0,5.0,Security strength of RSA in relation with the ...,NIST SP 800-57 §5.6.1 p.62–64 specifies a corr...,crypto.stackexchange.com.7z,8687,question,NaN,NaN,<code>Strength RSA modulus size\n 80 ...

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   site_alias             194 non-null    object
 1   tags                   90 non-null     object
 2   question_id            194 non-null    int64
 3   accepted_answer_id     64 non-null     float64
 4   answer_count           194 non-null    float64
 5   creation_date          194 non-null    object
 6   last_activity_date     194 non-null    object
 7   last_edit_date         139 non-null    object
 8   owner_id               186 non-null    float64
 9   score                  194 non-null    int64
 10  view_count             194 non-null    float64
 11  comment_count          194 non-null    float64
 12  title                  90 non-null     object
 13  body                   194 non-null    object
 14  site                   194 non-null    object
 15  id                     194 non-null    int64
 16  type                   194 non-null    object
 17  code                   0 non-null      float64
 18  languages              0 non-null      float64
 19  invalid_block_preview  194 non-null    object
dtypes: float64(7), int64(3), object(10)
memory usage: 30.4+ KB

In [37]:
df.drop_duplicates(inplace=True)

In [38]:
df.shape

(194, 20)