## Valid

In [29]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv('C:\K\social-media-dev-crawler\data\data_mining\s2\preprocessed_full_posts.csv')
df.head()

<>:4: SyntaxWarning: invalid escape sequence '\K'
<>:4: SyntaxWarning: invalid escape sequence '\K'
C:\Users\RESET Lab\AppData\Local\Temp\ipykernel_2604\277205348.py:4: SyntaxWarning: invalid escape sequence '\K'
  df = pd.read_csv('C:\K\social-media-dev-crawler\data\data_mining\s2\preprocessed_full_posts.csv')

,site_alias,tags,question_id,accepted_answer_id,answer_count,creation_date,last_activity_date,last_edit_date,owner_id,score,view_count,comment_count,title,body,site,id,type,code
0,crypto,chacha;stream-cipher,70094,70112.0,3.0,2019-04-26T22:37:10.927,2019-05-14T01:54:29.397,2021-10-07T07:59:29.080,28046.0,6,4432.0,4,Does ChaCha20 counter actually increment throu...,RFC defines:\n\n<code>state = constants | key ...,crypto.stackexchange.com.7z,70094,question,<code>state = constants | key | counter | nonc...
1,crypto,ctr;cryptocurrency;aes,55014,55044.0,2.0,2018-01-25T15:33:08.797,2018-01-30T15:51:38.750,2018-01-26T11:07:05.477,55389.0,4,19846.0,5,How insecure is AES-128-CTR to encrypt any kin...,I am using the Ethereum keystore file format t...,crypto.stackexchange.com.7z,55014,question,"<code>{\n ""crypto"" : {\n ""cipher"" : ..."
2,crypto,factoring;key-size;cryptanalysis;rsa,8687,8692.0,4.0,2013-06-11T16:36:12.377,2020-11-01T07:03:19.213,2017-04-13T12:48:22.170,214.0,48,38477.0,5,Security strength of RSA in relation with the ...,NIST SP 800-57 §5.6.1 p.62–64 specifies a corr...,crypto.stackexchange.com.7z,8687,question,<code>Strength RSA modulus size\n 80 ...
3,crypto,entropy;one-time-pad;random-number-generator;r...,8695,NaN,11.0,2013-06-12T00:09:58.983,2015-03-10T23:27:36.777,2013-12-28T10:22:50.893,4150.0,8,5411.0,16,Algorithm: How to use x and y mouse movement c...,Background:\n\nI'm making a program for fun as...,crypto.stackexchange.com.7z,8695,question,"<code>[478,702] \n[503,701] \n[581,687] ..."
4,crypto,rsa;keys;certificates;prime-numbers;public-key,12378,NaN,2.0,2013-12-16T22:53:54.490,2017-07-06T11:56:34.173,2013-12-16T23:11:16.457,10912.0,6,7324.0,5,What exactly is inside a private key?,"May sound stupid to many, but I would like to ...",crypto.stackexchange.com.7z,12378,question,<code>-----BEGIN RSA PRIVATE KEY-----\nMIIBPAI...

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   site_alias          250 non-null    object
 1   tags                159 non-null    object
 2   question_id         250 non-null    int64
 3   accepted_answer_id  115 non-null    float64
 4   answer_count        250 non-null    float64
 5   creation_date       250 non-null    object
 6   last_activity_date  250 non-null    object
 7   last_edit_date      186 non-null    object
 8   owner_id            242 non-null    float64
 9   score               250 non-null    int64
 10  view_count          250 non-null    float64
 11  comment_count       250 non-null    int64
 12  title               159 non-null    object
 13  body                250 non-null    object
 14  site                250 non-null    object
 15  id                  250 non-null    int64
 16  type                250 non-null    object
 17  code                250 non-null    object
dtypes: float64(4), int64(4), object(10)
memory usage: 35.3+ KB

In [31]:
df.drop_duplicates(inplace=True)

In [32]:
df.shape

(250, 18)

In [33]:
questions = df[df['type'] == 'question']
answers = df[df['type'] == 'answer']

In [34]:
questions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 159 entries, 0 to 187
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   site_alias          159 non-null    object
 1   tags                159 non-null    object
 2   question_id         159 non-null    int64
 3   accepted_answer_id  115 non-null    float64
 4   answer_count        159 non-null    float64
 5   creation_date       159 non-null    object
 6   last_activity_date  159 non-null    object
 7   last_edit_date      133 non-null    object
 8   owner_id            156 non-null    float64
 9   score               159 non-null    int64
 10  view_count          159 non-null    float64
 11  comment_count       159 non-null    int64
 12  title               159 non-null    object
 13  body                159 non-null    object
 14  site                159 non-null    object
 15  id                  159 non-null    int64
 16  type                159 non-null    object
 17  code                159 non-null    object
dtypes: float64(4), int64(4), object(10)
memory usage: 23.6+ KB

In [35]:
answers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 91 entries, 64 to 249
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   site_alias          91 non-null     object
 1   tags                0 non-null      object
 2   question_id         91 non-null     int64
 3   accepted_answer_id  0 non-null      float64
 4   answer_count        91 non-null     float64
 5   creation_date       91 non-null     object
 6   last_activity_date  91 non-null     object
 7   last_edit_date      53 non-null     object
 8   owner_id            86 non-null     float64
 9   score               91 non-null     int64
 10  view_count          91 non-null     float64
 11  comment_count       91 non-null     int64
 12  title               0 non-null      object
 13  body                91 non-null     object
 14  site                91 non-null     object
 15  id                  91 non-null     int64
 16  type                91 non-null     object
 17  code                91 non-null     object
dtypes: float64(4), int64(4), object(10)
memory usage: 13.5+ KB

In [36]:
p = df[(df['question_id'] == 8695) & (df['type'] == 'question')]
p

,site_alias,tags,question_id,accepted_answer_id,answer_count,creation_date,last_activity_date,last_edit_date,owner_id,score,view_count,comment_count,title,body,site,id,type,code
3,crypto,entropy;one-time-pad;random-number-generator;r...,8695,NaN,11.0,2013-06-12T00:09:58.983,2015-03-10T23:27:36.777,2013-12-28T10:22:50.893,4150.0,8,5411.0,16,Algorithm: How to use x and y mouse movement c...,Background:\n\nI'm making a program for fun as...,crypto.stackexchange.com.7z,8695,question,"<code>[478,702] \n[503,701] \n[581,687] ..."
32,crypto,random-number-generator;randomness;one-time-pa...,8695,NaN,11.0,2013-06-12T00:09:58.983,2015-03-10T23:27:36.777,2013-12-28T10:22:50.893,4150.0,8,5411.0,16,Algorithm: How to use x and y mouse movement c...,Background:\n\nI'm making a program for fun as...,crypto.stackexchange.com.7z,8695,question,"<code>[478,702] \n[503,701] \n[581,687] ..."
50,crypto,entropy;random-number-generator;randomness;one...,8695,NaN,11.0,2013-06-12T00:09:58.983,2015-03-10T23:27:36.777,2013-12-28T10:22:50.893,4150.0,8,5411.0,16,Algorithm: How to use x and y mouse movement c...,Background:\n\nI'm making a program for fun as...,crypto.stackexchange.com.7z,8695,question,"<code>[478,702] \n[503,701] \n[581,687] ..."

In [42]:
p = df[df['question_id'] == 12378]
p

,site_alias,tags,question_id,accepted_answer_id,answer_count,creation_date,last_activity_date,last_edit_date,owner_id,score,view_count,comment_count,title,body,site,id,type,code
168,crypto,NaN,12378,NaN,0.0,2017-07-05T10:44:06.590,2017-07-06T11:56:34.173,2017-07-06T11:56:34.173,48332.0,2,0.0,1,NaN,"Firstly, there are two common formats to store...",crypto.stackexchange.com.7z,48864,answer,NaN

## Invalid

In [37]:
df = pd.read_csv(r'C:\K\social-media-dev-crawler\data\data_mining\s2\invalid_codes.csv')
df.head()

,site_alias,tags,question_id,accepted_answer_id,answer_count,creation_date,last_activity_date,last_edit_date,owner_id,score,view_count,comment_count,title,body,site,id,type,code
0,crypto,file-encryption;cryptanalysis,72384,NaN,7.0,2019-08-05T11:28:18.697,2019-08-08T01:08:37.403,2019-08-07T18:27:14.967,8532.0,18,23047.0,11,How to check a file was encrypted (really & co...,I would like to audit how an implementation of...,crypto.stackexchange.com.7z,72384,question,<code>ent</code>
1,crypto,key-reuse;one-time-pad;cryptanalysis,2249,2250.0,3.0,2012-03-31T22:29:02.540,2016-01-31T10:22:32.350,2017-04-13T12:48:24.517,1867.0,79,93925.0,5,How does one attack a two-time pad (i.e. one t...,My question might appear the same as the quest...,crypto.stackexchange.com.7z,2249,question,<code>' '</code>\n\n<code>' '</code>
2,crypto,key-reuse;xor;ciphertext-only-attack;one-time-pad,88430,88496.0,2.0,2021-02-23T10:52:00.590,2024-11-14T19:00:56.130,2021-02-26T14:25:04.713,3941.0,4,18093.0,10,How to decrypt two images encrypted using XOR ...,I am trying to solve the following puzzle from...,crypto.stackexchange.com.7z,88430,question,<code>from binascii import unhexlify\n\nwith o...
3,crypto,authenticated-encryption;hash;rsa;signature;fi...,8104,8116.0,5.0,2013-04-24T15:51:00.203,2018-01-31T00:56:20.663,2013-04-24T17:03:21.083,6389.0,10,7163.0,18,Tamper-proofing log files,Problem Overview\n\nI want to securely store l...,crypto.stackexchange.com.7z,8104,question,<code>2013-01-01.log</code>\n\n<code>2013-01-0...
4,crypto,aes-gcm;gcm;aes,76177,NaN,3.0,2019-12-03T17:23:42.200,2019-12-06T11:23:35.187,2019-12-04T21:03:59.350,74873.0,9,33754.0,6,How to encrypt files using AES256-GCM cipher u...,I'm struggling to implement AES256-GCM on a Li...,crypto.stackexchange.com.7z,76177,question,<code>$ openssl aes-256-gcm\nAEAD ciphers not ...

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 745 entries, 0 to 744
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   site_alias          745 non-null    object
 1   tags                300 non-null    object
 2   question_id         745 non-null    int64
 3   accepted_answer_id  210 non-null    float64
 4   answer_count        745 non-null    float64
 5   creation_date       745 non-null    object
 6   last_activity_date  745 non-null    object
 7   last_edit_date      469 non-null    object
 8   owner_id            717 non-null    float64
 9   score               745 non-null    int64
 10  view_count          745 non-null    float64
 11  comment_count       745 non-null    int64
 12  title               300 non-null    object
 13  body                745 non-null    object
 14  site                745 non-null    object
 15  id                  745 non-null    int64
 16  type                745 non-null    object
 17  code                364 non-null    object
dtypes: float64(4), int64(4), object(10)
memory usage: 104.9+ KB

In [39]:
df.drop_duplicates(inplace=True)

In [40]:
df.shape

(596, 18)