In [1]:
import pandas as pd

In [3]:
df = pd.read_xml('../dump/stackexchange_20240930/stackexchange_20240930/crypto.meta.stackexchange.com/Posts.xml')
df.head()

,Id,PostTypeId,CreationDate,Score,ViewCount,Body,OwnerDisplayName,LastActivityDate,Title,Tags,...,CommentCount,ContentLicense,LastEditorDisplayName,LastEditDate,AcceptedAnswerId,ClosedDate,ParentId,CommunityOwnedDate,OwnerUserId,LastEditorUserId
0,52,1,2011-07-25T20:16:04.240,4,71.0,"<p>Ok so as has been raised a couple of times,...",user46,2011-07-28T19:19:40.417,Can we invite users to the private beta?,<discussion><support><beta>,...,2,CC BY-SA 3.0,None,None,NaN,None,NaN,None,NaN,NaN
1,119,1,2011-11-30T10:51:22.803,2,29.0,"<p>So, after <a href=""http://chat.stackexchang...",user46,2011-11-30T10:51:22.803,Chat event #2 - planning?,<discussion><chat>,...,1,CC BY-SA 3.0,None,None,NaN,None,NaN,None,NaN,NaN
2,141,1,2012-03-05T22:46:43.990,6,59.0,"<p>Then <a href=""http://chat.stackexchange.com...",user46,2012-03-05T22:46:43.990,Interested in the SE moderation process?,<discussion><chat><moderation>,...,0,CC BY-SA 3.0,None,None,NaN,None,NaN,None,NaN,NaN
3,1166,4,2019-01-08T18:27:57.993,0,NaN,Unanswered questions are those questions which...,user63532,2019-01-14T00:38:46.117,None,None,...,0,CC BY-SA 4.0,user63532,2019-01-14T00:38:46.117,NaN,None,NaN,None,NaN,NaN
4,58,1,2011-08-01T12:09:57.447,2,82.0,"<p>On the <a href=""http://area51.stackexchange...",user93,2011-08-01T14:35:45.450,Do Area51 recommendations apply to public beta...,<discussion><beta>,...,3,CC BY-SA 3.0,None,None,60.0,2015-03-06T15:47:02.593,NaN,None,NaN,NaN

In [4]:
df = pd.read_xml('../dump/stackexchange_20240930/stackexchange_20240930/crypto.meta.stackexchange.com/Posts.xml',
                 xpath='//row')
df.head()

ERROR! Session/line number was not unique in database. History logging moved to new session 132

,Id,PostTypeId,CreationDate,Score,ViewCount,Body,OwnerDisplayName,LastActivityDate,Title,Tags,...,CommentCount,ContentLicense,LastEditorDisplayName,LastEditDate,AcceptedAnswerId,ClosedDate,ParentId,CommunityOwnedDate,OwnerUserId,LastEditorUserId
0,52,1,2011-07-25T20:16:04.240,4,71.0,"<p>Ok so as has been raised a couple of times,...",user46,2011-07-28T19:19:40.417,Can we invite users to the private beta?,<discussion><support><beta>,...,2,CC BY-SA 3.0,None,None,NaN,None,NaN,None,NaN,NaN
1,119,1,2011-11-30T10:51:22.803,2,29.0,"<p>So, after <a href=""http://chat.stackexchang...",user46,2011-11-30T10:51:22.803,Chat event #2 - planning?,<discussion><chat>,...,1,CC BY-SA 3.0,None,None,NaN,None,NaN,None,NaN,NaN
2,141,1,2012-03-05T22:46:43.990,6,59.0,"<p>Then <a href=""http://chat.stackexchange.com...",user46,2012-03-05T22:46:43.990,Interested in the SE moderation process?,<discussion><chat><moderation>,...,0,CC BY-SA 3.0,None,None,NaN,None,NaN,None,NaN,NaN
3,1166,4,2019-01-08T18:27:57.993,0,NaN,Unanswered questions are those questions which...,user63532,2019-01-14T00:38:46.117,None,None,...,0,CC BY-SA 4.0,user63532,2019-01-14T00:38:46.117,NaN,None,NaN,None,NaN,NaN
4,58,1,2011-08-01T12:09:57.447,2,82.0,"<p>On the <a href=""http://area51.stackexchange...",user93,2011-08-01T14:35:45.450,Do Area51 recommendations apply to public beta...,<discussion><beta>,...,3,CC BY-SA 3.0,None,None,60.0,2015-03-06T15:47:02.593,NaN,None,NaN,NaN